//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOY.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chief
    {
        public int ID_Chief { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> DateOfEmployment { get; set; }
        public Nullable<int> WorkExp { get; set; }
        public string FIO { get; set; }
    }
}
