//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOY.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildrenInGroup
    {
        public int id_ChilGroup { get; set; }
        public Nullable<int> id_Children { get; set; }
        public Nullable<int> id_Group { get; set; }
    
        public virtual Children Children { get; set; }
        public virtual Group Group { get; set; }
    }
}
