//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOY.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kindergartener
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kindergartener()
        {
            this.Kindergarten = new HashSet<Kindergarten>();
        }
    
        public int ID_Kindergartener { get; set; }
        public Nullable<int> id_Position { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string Phone { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> DateOfEmployment { get; set; }
        public Nullable<int> WorkExp { get; set; }
        public string FIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kindergarten> Kindergarten { get; set; }
        public virtual Position Position { get; set; }
    }
}
