//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOY.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kindergarten
    {
        public int ID_Kindergarten { get; set; }
        public string Cabinet { get; set; }
        public string Floor { get; set; }
        public Nullable<int> id_Group { get; set; }
        public Nullable<int> id_Kindergartener { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Kindergartener Kindergartener { get; set; }
    }
}
