//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOY.dataFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DOYEntities1 : DbContext
    {
        public DOYEntities1()
            : base("name=DOYEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chief> Chief { get; set; }
        public virtual DbSet<Children> Children { get; set; }
        public virtual DbSet<ChildrenInGroup> ChildrenInGroup { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Kindergarten> Kindergarten { get; set; }
        public virtual DbSet<Kindergartener> Kindergartener { get; set; }
        public virtual DbSet<Parent> Parent { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ParentChildren> ParentChildren { get; set; }
    }
}
