//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOY.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentChildren
    {
        public int ID_Contract { get; set; }
        public string SurnameChild { get; set; }
        public string FirstNameChild { get; set; }
        public string MiddleNameChild { get; set; }
        public Nullable<System.DateTime> DateOfBirthChild { get; set; }
        public Nullable<int> AgeChild { get; set; }
        public byte[] ImageChild { get; set; }
        public string FIOChild { get; set; }
        public int ID_Children { get; set; }
        public int ID_Parent { get; set; }
        public string SurnamePar { get; set; }
        public string FirstNamePar { get; set; }
        public string MiddleNamePar { get; set; }
        public Nullable<System.DateTime> DateOfBirthPar { get; set; }
        public Nullable<int> AgePar { get; set; }
        public byte[] ImagePar { get; set; }
        public string PhonePar { get; set; }
        public string FIOPar { get; set; }
        public Nullable<int> Pay { get; set; }
        public Nullable<int> id_Group { get; set; }
        public Nullable<System.DateTime> DateContract { get; set; }
    }
}
